### ISSUE TITLE
Implement a SMTP Submission server.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/client#2]
There's probably library code out there that handles this.  If not the relevant RFCs are:
 * https://tools.ietf.org/html/rfc5321
 * https://tools.ietf.org/html/rfc6409

**Comment by david415** [comment]
here's a simple SMTP server:
https://github.com/bradfitz/go-smtpd

we could probably just start from that and modify it to be suitable for our needs. changes like removing the authentication (since it'll run locally on the client endpoint).

**Comment by Yawning** [comment]
https://github.com/flashmob/go-guerrilla looks tested and sufficiently well documented (Also note that SMTP-AUTH is mandatory for MSAs).

**Comment by Yawning** [comment]
This also looks sensible: https://github.com/siebenmann/smtpd though may be too minimalistic for our needs.

**Comment by david415** [comment]
i've implemented the basics using that last smtp library https://github.com/siebenmann/smtpd
it works fine... here's my dev branch so far:

https://github.com/Katzenpost/client/tree/add_sphinx_submission.0

i'll be proxying to the provider as soon as the mixnet wire protocol is stabilized.

**Comment by david415** [comment]
i think i'll close this ticket since in my dev branches i do have a working SMTP server that does the mail from and rcpt to checks and filters the MIME headers etc.
