### ISSUE TITLE
Key Directory Service via Authentication Server

### ISSUE THREAD

**Issue by Valodim** [katzenpost/client#31]
(not sure where this fits best, so just putting it here) see also https://github.com/katzenpost/server/issues/27

For discussion:

To achieve asynchronous end-to-end encryption, we need a way for clients to
place keys in a well-known location, that can then be requested by other
clients. We came up with a proposal that builds on the existing mixnet design,
requiring no changes to the server implementation, and that can be built as
another layer around the client library.

The idea is to have an authentication server that runs on the provider and takes
care of authenticating the provider's users, but that also participates in the
mixnet as a service in the privileged namespace. This service primarily exposes
a user registration interface of some kind, and takes care of authenticating
users for the provider (via the Exists + IsValid interface). As a secondary
feature, it stores an identity key for each user. This identity key can be
requested (anonymously) by clients via the mixnet, using a simple query to the
privileged service name that includes a SURB for the reply.

As a simple example:

- A registers an account on provider P, sending her identity key IA to +K@P
- B registers an account on provider Q, sending his identity key IB to +K@Q
- A intends to send a message to B:
  - A sends a request for IB to +K@Q, including a SURB
  - +K@Q replies to A via SURB with IB
  - A encrypts her message to IB, and sends it to B via the mixnet

Instead of directly encrypting to IB, Alice could of course use a more involved
scheme, for example with an authenticated Diffie-Hellman. It's also
straightforward to layer the Signal protocol on top of this, although prekeys
would require additional support by the key service.

Queries for keys are anonymous by design, which makes it hard for a key service
to equivocate any user's key. A request for Bob's identity IB might even come
from B himself, to check whether KQ is genuine.

**Comment by david415** [comment]
this all sounds good to me. maybe we should implement it. firstly, however, we need to unfuck our client library and bindings because right now that code is not stable at all.
