### ISSUE TITLE
Mixnet Services ("Bots")

### ISSUE THREAD

**Issue by Valodim** [katzenpost/client#32]
For discussion:

With the message passing and SURB architecture, Katzenpost is very suitable for
services that yield automated replies ("Bots", they call 'em these days).

### Dead-drop / Attachment Service

Sending large messages might not be desirable to clients that have restricted
bandwidth. As an alternative, it would be possible to have "dead-drop" services:

For this scenario, an Alice A@P wants to send a large message M to a Bob B@Q.
Given an attachment service T@S, this could work as follows:
- A@P encrypts M to B@Q as M'
- A@P sends M' to T@S, together with a SURB
- T@S saves M', assigns a token TM to it, and sends that token to Alice via SURB
- A@P receives TM, and sends it to B@Q as part of an encrypted message
- B@Q receives the message including TM
- B@Q sends TM and a SURB to T@S
- T@S replies with M' via SURB, then deletes M'

If Alice didn't want to disclose her use of T@S to Bob, she could also send Bob
a SURB to T@S. However, this might not be desirable as "attachments" lifetimes
likely exceed that of a SURB.

### Metadata Storage

As a generalization to the above use case of key discovery, services can store
arbitrary metadata on behalf of users. As a simple instance of this, users
authenticate a key-time-value pair with their identity key, and send it to a
service. Other participants of the mixnet can then retrieve this data
(anonymously) by requesting it by the well-known key.

As an example use case, Alice A@P with identity key IA wants to associate an
avatar AV with her address given metadata service +M@P:
- A@P authenticates a tuple (IA, "avatar", $time, AV) with IA, and sends it to +M@P
- +M@P verifies the tuple and stores it (possibly replacing an older one)
- B@Q sends a request for (IA, "avatar") to +M@P, including a SURB
- +M@P replies with (IA, "avatar", $time, AV) via SURB

Related #31, https://github.com/katzenpost/server/issues/27

**Comment by david415** [comment]
This doesn't save bandwidth at all. It does however make the location hiding properties stronger and we like that but we aren't going to do this work any time soon. We are taking an incremental approach to design and development where the first step is the write specifications and have them carefully reviewed before implementing. So... in the future yes we can have nice things such as these message aggregation schemes that offer stronger location hiding properties than just the Loopix Provider model. That same hopeful future would also include spec writing and review before implementation.
