### ISSUE TITLE
which implementation of exponential distribution sampler to use?

### ISSUE THREAD

**Issue by david415** [katzenpost/client#6]
Our use of the Poisson mix strategy requires clients to set the per route hop delays from samples of an exponential distribution which has a parameter called mu; which implementation to use?

https://github.com/leesper/go_rng/blob/master/poisson.go
https://github.com/atgjack/prob/blob/master/poisson.go

**Comment by Yawning** [comment]
https://github.com/Katzenpost/core/blob/master/crypto/rand/math.go#L88

That one.
